In [1]:
import pandas as pd
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

C:\Users\Excellent Store\AppData\Local\Temp\ipykernel_2016\4185938564.py:4: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
C:\Users\Excellent Store\AppData\Local\Temp\ipykernel_2016\4185938564.py:5: UserWarning: 
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html


In [5]:
import plotly.graph_objects as go
import plotly.express as px
import numpy as np

In [11]:
np.random.seed(1)
x=np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [7]:
y1=np.random.randint(50,500,size=12)
y1

array([ 87, 285, 446, 122, 305, 443, 253, 183, 385, 498, 194, 179],
      dtype=int32)

In [10]:
np.random.seed(2)
y2=np.random.randint(50,500,size=12)
y2

array([218,  65, 122,  72, 349, 125, 410, 313, 212, 483, 145, 125],
      dtype=int32)

In [19]:
np.random.seed(3)
y3=np.random.randint(50,500,size=12)
y3

array([412, 202, 299, 181, 490, 306, 327, 197, 252, 413, 219, 188],
      dtype=int32)

In [28]:
np.random.seed(12)
x=np.arange(12)
y=np.random.randint(50,500,size=12)

df = pd.DataFrame({"x": x, "y": y})

fig = px.scatter(df, x='x', y='y', title=f'Distribution in {12}')
fig

In [ ]:
plot1=go.Figure(data=go.Scatter(x=x,y=y))
plot1

In [16]:
plot2=go.Figure(data=go.Scatter(x=x,y=y2))
plot2

In [20]:
plot3=go.Figure(data=go.Scatter(x=x,y=y3))
plot3

In [ ]:

app2 = dash.Dash()

colors = {'text': 'blue'}

app2.layout = html.Div(children=[
    html.H1('Seed Distribution', 
            style={'textAlign': 'center', 'color': colors['text'], 'font-size': 30}),
    html.Div([
        "Input Seed: ", 
        dcc.Input(id='input-sd', value=1, type='number', 
                  style={'height': '50px', 'font-size': 30})
    ], style={'font-size': 40}),
    html.Br(),
    html.Br(),
    html.Div(dcc.Graph(id='scatterplt'))
])
 

@app2.callback(
    Output('scatterplt', 'figure'),
    Input('input-sd', 'value')
)
def update_graph(input_value):
    
    np.random.seed(input_value)
    x=np.arange(12)
    y=np.random.randint(50,500,size=12)

    fig = go.Figure(data=go.Scatter(x=x,y=y))
    return fig
 

if __name__ == '__main__':
    app2.run_server(port=8003,host='127.0.0.1')